name: flutter_aitriage
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  dio: ^5.3.1
  google_fonts: ^5.1.0
  get_storage: ^2.1.1
  shake: ^2.2.0
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/aitriage_core/asset/language/
    - lib/aitriage_core/asset/image/


