name: flutter_aitriage
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # core
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  dio: ^5.3.1
  google_fonts: ^5.1.0
  get_storage: ^2.1.1
  shake: ^2.2.0
  flutter_svg: ^2.0.7
  introduction_screen: ^3.1.11
  flutter_secure_storage: ^8.0.0
  tutorial_coach_mark: ^1.2.9
  syncfusion_flutter_charts: ^22.2.8
  sprintf: ^7.0.0
  pin_code_fields: ^8.0.1
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  open_mail_app: ^0.4.5
  connectivity_plus: ^4.0.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_core: ^2.15.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - lib/aitriage_core/asset/language/
    - lib/aitriage_core/asset/image/
    - lib/aitriage_core/asset/key/


