class Patient {
  int? id;
  String? code;
  String? fullName;
  String? firstName;
  String? lastName;
  int? idNumber;
  String? phoneCode;
  String? phone;
  bool? phoneVerified;
  String? phoneExt1;
  String? phoneExt2;
  String? email;
  bool? emailVerified;
  String? emailExt1;
  String? emailExt2;
  String? briefInfo;
  String? birthday;
  int? yearOfBirth;
  String? avatar;
  String? gender;
  String? marriedStatus;
  int? categoryIds;
  int? raceId;
  int? nationalityId;
  int? countryId;
  int? stateId;
  int? cityId;
  int? districtId;
  int? wardId;
  String? address;
  String? zipCode;
  int? refCustomerId;
  String? refCustomerFullName;
  String? description;
  String? lastActivityDate;
  String? dispStatus;
  int? locationId;
  int? accountId;
  String? accountNo;
  int? createdBy;
  String? updatedBy;
  String? deletedBy;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? raceName;
  String? cityName;
  String? countryName;
  String? stateName;
  String? nationalityName;
  int? age;

  Patient.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    code = json['code'];
    fullName = json['fullName'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    idNumber = json['idNumber'];
    phoneCode = json['phoneCode'];
    phone = json['phone'];
    phoneVerified = json['phoneVerified'];
    phoneExt1 = json['phoneExt1'];
    phoneExt2 = json['phoneExt2'];
    email = json['email'];
    emailVerified = json['emailVerified'];
    emailExt1 = json['emailExt1'];
    emailExt2 = json['emailExt2'];
    briefInfo = json['briefInfo'];
    birthday = json['birthday'];
    yearOfBirth = json['yearOfBirth'];
    avatar = json['avatar'];
    gender = json['gender'];
    marriedStatus = json['marriedStatus'];
    categoryIds = json['categoryIds'];
    raceId = json['raceId'];
    nationalityId = json['nationalityId'];
    countryId = json['countryId'];
    stateId = json['stateId'];
    cityId = json['cityId'];
    districtId = json['districtId'];
    wardId = json['wardId'];
    address = json['address'];
    zipCode = json['zipCode'];
    refCustomerId = json['refCustomerId'];
    refCustomerFullName = json['refCustomerFullName'];
    description = json['description'];
    lastActivityDate = json['lastActivityDate'];
    dispStatus = json['dispStatus'];
    locationId = json['locationId'];
    accountId = json['accountId'];
    accountNo = json['accountNo'];
    createdBy = json['createdBy'];
    updatedBy = json['updatedBy'];
    deletedBy = json['deletedBy'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    deletedAt = json['deletedAt'];
    raceName = json['raceName'];
    cityName = json['cityName'];
    countryName = json['countryName'];
    stateName = json['stateName'];
    nationalityName = json['nationalityName'];
    age = json['age'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['fullName'] = fullName;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['idNumber'] = idNumber;
    data['phoneCode'] = phoneCode;
    data['phone'] = phone;
    data['phoneVerified'] = phoneVerified;
    data['phoneExt1'] = phoneExt1;
    data['phoneExt2'] = phoneExt2;
    data['email'] = email;
    data['emailVerified'] = emailVerified;
    data['emailExt1'] = emailExt1;
    data['emailExt2'] = emailExt2;
    data['briefInfo'] = briefInfo;
    data['birthday'] = birthday;
    data['yearOfBirth'] = yearOfBirth;
    data['avatar'] = avatar;
    data['gender'] = gender;
    data['marriedStatus'] = marriedStatus;
    data['categoryIds'] = categoryIds;
    data['raceId'] = raceId;
    data['nationalityId'] = nationalityId;
    data['countryId'] = countryId;
    data['stateId'] = stateId;
    data['cityId'] = cityId;
    data['districtId'] = districtId;
    data['wardId'] = wardId;
    data['address'] = address;
    data['zipCode'] = zipCode;
    data['refCustomerId'] = refCustomerId;
    data['refCustomerFullName'] = refCustomerFullName;
    data['description'] = description;
    data['lastActivityDate'] = lastActivityDate;
    data['dispStatus'] = dispStatus;
    data['locationId'] = locationId;
    data['accountId'] = accountId;
    data['accountNo'] = accountNo;
    data['createdBy'] = createdBy;
    data['updatedBy'] = updatedBy;
    data['deletedBy'] = deletedBy;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    data['raceName'] = raceName;
    data['cityName'] = cityName;
    data['countryName'] = countryName;
    data['stateName'] = stateName;
    data['nationalityName'] = nationalityName;
    data['age'] = age;
    return data;
  }
}